### ISSUE TITLE
Hide elements other than the ones matched

### ISSUE THREAD

**Issue by ghost** [Haroenv/holmes#108]
Hi, thanks for the handy library.

I have listings to search like [this picture](https://ibb.co/0GnLGJt). As you can see, so much elements in there.
Search successfully runs, however, in my case I want to hide parent element.

my `find: '.row .col p',` works well for the targeted text to search, however I want not only hide `p` element but the whole `row`.

optional: is there a way to search in two elements ? say for example : `find: ['.row .col p', '.row .col h3']`. (Probably I am asking too much for what is intended, excuse me for this)

thanks a lot !!

**Comment by ghost** [comment]
Sorry for the precipitation and second question: I put `find: '.row .col p, .row .col h3',` (querySelectorAll as indicated) and it works. But the first issue holds.

**Comment by Haroenv** [comment]
I don't think I fully understand what you are having an issue with. Could you create a sandbox with what you made so far? 

I've made a demo sandbox here: https://codesandbox.io/s/nifty-lalande-s3buu

**Comment by ghost** [comment]
Hello @Haroenv ,
thank you for your time.
I just wrapped the first `blockquote` with a div. If you search for `I am` for example, (as intended initially from the library) all other `blockquote`s are hidden, and `h3` is not. I want to hide a different element, **the parent**.

https://codesandbox.io/s/naughty-sammet-4l02d

Theoritically, separate what we search from what we hide/show (at least offer, say `parent` to hide in this case)


Thanks !

**Comment by ghost** [comment]
my bad, we can get a reference to elements thanks to event already there.
I tried:
```

   try {
      var h = holmes({
         input: '.search input',
         find: '.row .col h3',
         placeholder: '<h3>— No results, my dear Watson. —</h3>',
         mark: false,
         hiddenAttr: true,
         class: {
            visible: 'visible',
            hidden: 'hidden'
         },
         onHidden(el) {
            if(el.parentElement)
               el.parentElement.style = 'display: none'
            console.log('hidden', el);
         },
         onFound(el) {
            console.log('found', el);
         },
         onInput(el) {
            console.log('input', el);
         },
         onVisible(el) {
            if(el.parentElement)
               el.parentElement.style = 'display: block'
            console.log('visible', el);
         },
         onEmpty(el) {
            console.log('empty', el);
         }
      });
   } catch (error) {
      console.log("Probably running where there is no list in HTML | ERROR: ", error.message)
   }
```

It is working !
Thanks a lot !!

**Comment by ghost** [comment]
all I had to do is to put the parent div. and everything inside is looked for and shown/hidden. so All is fine, 

my bad, sorry for that.

**Comment by Haroenv** [comment]
Glad you found a solution, I missed your messages! Hope you have a great time using Holmes :)
