### ISSUE TITLE
dynamic content

### ISSUE THREAD

**Issue by Haroenv** [Haroenv/holmes#17]
if the content is dynamic, on the places aligned in the code the elements should be queried again. 

If you want this feature, leave a comment or a thumbs up and I'll do it.

**Comment by LukyVj** [comment]
Can you give more explainations ?

**Comment by Haroenv** [comment]
Currently the `querySelectorAll` to get the search content is only executed once. My proposal is to add a new key to options (for example `continuous: true`, or `dynamic`, `interactive`) which will do the `querySelectorAll` for every input.

**Comment by Haroenv** [comment]
fixed in #29
