### ISSUE TITLE
When I clear the search input with cmd+a (or ctrl+a) the list isn't being reloaded.

### ISSUE THREAD

**Issue by robbporto** [Haroenv/holmes#23]
I fixed this.

Just created this issue to keep record and make a reference to the pull request.

**Comment by robbporto** [comment]
Here: #24!

**Comment by Haroenv** [comment]
Aha, I didn't notice that happened. I accidentally created this bug in #22 so I'll revert that rather than merging your pull request if that's fine. Have a nice day and let know what you think b
