### ISSUE TITLE
Demo on readme / website mismatch

### ISSUE THREAD

**Issue by LukyVj** [Haroenv/holmes#34]
![](http://puu.sh/ptwpP/e46018a1a6.png) 

VS 

![](http://puu.sh/ptwqB/d3d5e59819.png)

**Comment by Haroenv** [comment]
On purpose I guess. I don't want to overload the user with options

**Comment by LukyVj** [comment]
hmm yeah.. Well, I think it's still better to have something consistant. 
Or, you could make show on the demo, the most basic setup ( I guess only the input / find ).

And add a link below to see the "complete parameters available". 

I know it's already the case, but I think it's misleading. Better make it clearer.

**Comment by Haroenv** [comment]
Yeah, good point, maybe the simplest setup and elaborate behind something like a `details` (that also works on FF). I'll look into it
