### ISSUE TITLE
Not filtering content...

### ISSUE THREAD

**Issue by kricir** [Haroenv/holmes#37]
I am not sure what I am doing wrong, as it appears that everything on the plugin is working fine for me other than, changing the classes on my elements from visible to hidden.

I have tried basically to make a complete replica of your page, minus that my content is being loaded from the database, on load each of the elements gets the class of "visible" applied, but then I get nothing as I start to type in my input field.

Please feel free to look here: http://ncm.web50.iwmstage.com/index.php/association-lookup

I am hoping that you may notice something that I have done wrong, and can just as easily point out the solution for me?

**Comment by Haroenv** [comment]
I'll take a look, I don't see anything immediately wrong though

**Comment by Haroenv** [comment]
Okay, I found what you did wrong. You defined `input` as `.search input`, which will match the hidden input in the search window on top. 

``` html
<div class="search pull-right">
  <div class="search-container">
    <form action="http://ncm.web50.iwmstage.com/index.php/search" method="get" class="ccm-search-block-form">
      <!--<h3>-->
      <!--</h3>-->
      <input name="search_paths[]" type="hidden" value=""> <!-- this here matches options.input -->
      <input name="query" type="text" placeholder="Search" value="" class="ccm-search-block-text">
      <input name="submit" type="submit" class="btn btn-default ccm-search-block-submit">
    </form>
  </div>
</div>
```

As you see here the `hidden` search matches the querySelector before the input you actually want to target. By changing `view.js` to a unique querySelector like this: 

``` js
holmes({
    input: '.search input[type=search]',
    find: '.msv-location-map-list blockquote',
    placeholder: '<h3>— No results, my dear Watson. —</h3>',
    class: {
        visible: 'visible',
        hidden: 'hidden'
    }
});
```

I'm getting correct filtering. Feel free to reopen if you find this answer insufficient.
