### ISSUE TITLE
https://haroen.me/holmes/ web page problem

### ISSUE THREAD

**Issue by sahinyanlik** [Haroenv/holmes#79]
Even holmes able to find one item, still get --No results, my dear Watson. —

**Comment by Haroenv** [comment]
Thanks for letting me know. There was something wrong with the moment I hide/show the placeholder but I haven't got around to fixing it yet. 

However I already have #78 for tracking this. 

Feel free to search for the problem if you want

**Comment by Haroenv** [comment]
fixed @sahinyanlik FYI
