### ISSUE TITLE
Broken? Firefox issue?

### ISSUE THREAD

**Issue by ADRDev** [Haroenv/holmes#83]
I found this package today and it seems to do exactly what I want. Except.. I can't get it to work.

I installed it via npm, put a basic `<input type="search">` and set it up like so 
```
var h = holmes({
                input: 'input[type=search]',
                find: 'label',
                class: {
                    visible: 'highlight',
                    hidden: 'hidden'
                },
                hiddenAttr: true,
                mark: true
            });
```

Nothing appears to happen, and nothing shows up in console either.

The demo page doesn't work properly for me either.  As I type I get `TypeError: t.textContent.toLowerCase(...).includes is not a function` errors in the console.

These may be separate issues, I'm not sure.

**Comment by Haroenv** [comment]
Hey, thanks for wanting to use Holmes and sorry if it didn't work as expected. Could you tell me how you loaded it if you installed it via npm?

**Comment by Haroenv** [comment]
The demo works for me in Firefox, what version are you using?

**Comment by ADRDev** [comment]
Thanks for the quick reply!

I'm using Firefox ESR 38.8.0

I installed via npm install --save holmes.js

**Comment by Haroenv** [comment]
The Firefox issue could be pretty easy to solve if it was version < 40, since there string.prototype.includes is apparently called string.prototype.contains. I didn't know that 

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/includes

That is however probably another issue than the installing one.

**Comment by Haroenv** [comment]
So you downloaded it with npm, but how do you use it in your script, is it in `<script src=node_modules/holmes.js/js/holmes.js></script>`, via a bundler or even something else? 😄

**Comment by ADRDev** [comment]
Ah, it's being loaded via gulp/webpack.

Although, I just tried including through <script> tag directly and it didn't change anything.

**Comment by Haroenv** [comment]
Could you provide me with a project I could clone to figure out what's actually wrong?

**Comment by ADRDev** [comment]
I can't share the code (work).

Progress has been made however. I didn't realize I needed to call `h.start();` after I did that now I get the same error the demo page was giving me `TypeError: t.textContent.toLowerCase(...).includes is not a function`

**Comment by Haroenv** [comment]
Okay, then this issue is fixed, since #84 is fixed locally for me, in a few minutes I'll publish a new patch 😄

**Comment by ADRDev** [comment]
Now, that is what I call quality support!

**Comment by Haroenv** [comment]
Does the site work for you now (you might need to clear your cache). I haven't pushed a version to npm yet

**Comment by Haroenv** [comment]
published as 1.16.4

**Comment by ADRDev** [comment]
Yes, the demo works now! Thank you!

**Comment by Haroenv** [comment]
tip top, thanks for catching the error 👍
