### ISSUE TITLE
Catch when a .find isn’t a valid queryselector

### ISSUE THREAD

**Issue by Haroenv** [Haroenv/holmes#86]
Let’s say you accidentally add `find: ‘.’` or other invalid values. Now it would throw and not clean up properly. 

Checking should happen somewhere around [here](https://github.com/Haroenv/holmes/blob/512830f7179e1e3c6dd631dd14c97ee90e033ecb/js/main.js#L373-L378)

A try/catch should do the trick I think. In the catch block the cleaning up could happen (calling h.stop could not work, so manually do what already needs to be removed like placeholder) then we should throw with a descriptive error saying that .find was bad

**Comment by ghost** [comment]
Referencing https://stackoverflow.com/questions/16257006/regex-validator-for-queryselectorall-argument

Have you considered a regex or simply calling the querieSelector in the block of code at line 380?
My initial solution in mind would be to coerce to lower/upper and evaluate the characters of the string[index 0, and 1, or -1] from character codes but I am unaware if that would conflict with character encoding or something and it only covers the most basic case of validating a class or id. Have you considered the extent of a solution that you would accept? Regex isn't my strongest tool yet. Checking if querieSelector() seems the best route. RFC @Haroenv 
Sincerely, @etisdew

Throws a SYNTAX_ERR exception if the specified group of selectors is invalid and null if nothing is found.

**Comment by Haroenv** [comment]
Thanks for looking at this! I’d rather not parse for a correct queryselector manually because that’s bound to be wrong in some crazy cases. What I described in original issue was to catch when something goes wrong and fix the broken things. Does that make sense?

Feel free to make a pr with anything you think could work

**Comment by Haroenv** [comment]
Actually just rethrowing and relying on the platform makes much more sense. Closing
