### ISSUE TITLE
Does main.js need to be hosted?

### ISSUE THREAD

**Issue by dakshshah96** [Haroenv/holmes#91]
Hi, I'd like to host your library, holmes on [cdnjs](https://github.com/cdnjs/cdnjs) — It is one of the most famous free and public web front-end CDN services which is used by [~1,143,000 websites](https://trends.builtwith.com/cdn/CDN-JS) worldwide.

As far as I can comprehend, the following files need to be hosted:
```
js/holmes.js
js/holmes.es.js
```
Should the file `js/main.js` also be included? Also, please let me know if any other files should be hosted so developers can directly use holmes from [CDNJS](https://cdnjs.com).

**Comment by Haroenv** [comment]
No, because that's written in Es2015 with flow annotations, so it can't be ran in browsers. The es build can be ran in browsers that are very modern (latest safari for ex). Thanks

**Comment by dakshshah96** [comment]
Thanks @Haroenv for the quick response. So I'll be including just `holmes.js` and `holmes.es.js`.
