### ISSUE TITLE
I want to use custom stringIncludes

### ISSUE THREAD

**Issue by chimame** [Haroenv/holmes#95]
Thank you for a wonderful product.

## Problems and suggestions
The current implementation is a search that shows or hides the HTML element by partially matching the search value.
AND, OR search can not be performed.

## Countermeasure
Set `stringIncludes` as the default search, pass the search function as an option, and display or hide the HTML element according to the result of the passed search function.

**Comment by Haroenv** [comment]
Seems reasonable. What kind of searchFunction would you want to provide? 

The signature would be: 

```js
shouldShow(element.textContent.toLowerCase(), this.searchString);
```

and it should return a boolean which is true, if the condition results in that element needing to be shown, and false if it needs to be hidden.

**Comment by Haroenv** [comment]
I released a beta which has an option `shouldShow` as a function, which takes as first argument the text of the element, and as second argument the text of the input right now. You should return `true` if that element should be visible, false if it should be hidden

Test it on `yarn add holmes.js@beta`

**Comment by chimame** [comment]
Thank you @Haroenv 
It is the specification as I suggested.

**Comment by Haroenv** [comment]
okay, merging it and deploying

**Comment by Haroenv** [comment]
Released as https://github.com/Haroenv/holmes/releases/tag/v1.17.2

**Comment by Haroenv** [comment]
I’d love to see what you built with Holmes, care to send me it when it’s done?
